body:
 - type: textarea
   id: description
   attributes:
    label: Description
    description: Give us a brief description of the feature or enhancement you would like
   validations:
    required: true

 - type: textarea
   id: additional-information
   attributes:
    label: Additional Information
    description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
