name: "📚 Documentation needs improvement"
description: "Request a documentation improvement to help us improve the project."
labels:
 - "docs"
assignees:
 - "igorkowalczyk"
body:
 - type: markdown
   id: intro
   attributes:
    value: "Before opening this issue to request a docs improvement, is this something you can help us with? Your contributions are welcomed and appreciated. If you're able to, please consider submitting a pull request with the changes you'd like to see. If you're not able to, please fill out the form below to help us understand what needs to be improved."

 - type: textarea
   id: page
   attributes:
    label: "What page(s) need to be changed or created?"
    description: "Please provide a link to the page(s) that need to be changed or created."
    placeholder: "e.g. https://example.com/docs/page"
   validations:
    required: true

 - type: textarea
   id: issue
   attributes:
    label: "What documentation issue do you want to solve?"
    description: "Please explain your issue in as much detail as possible."
    placeholder: "e.g. The page is missing information about..."
   validations:
    required: true

 - type: textarea
   id: solution
   attributes:
    label: "What do you think is the correct solution?"
    description: "Please explain what you think the correct solution is."
    placeholder: "e.g. The page should include information about..."
   validations:
    required: true

 - type: textarea
   id: additional-comments
   attributes:
    label: "Additional comments"
    description: "Is there anything else that's important for us to know?"
   validations:
    required: false
